version: "3"

services:
  web:
    image: node:alpine
    working_dir: /usr/app
    volumes:
      - ./web:/usr/app
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn start"
    depends_on:
      - api

  api:
    image: node
    working_dir: /usr/app
    volumes:
      - ./api:/usr/app
    ports:
      - 3333:3333
    environment:
      - npm_config_build_from_source=true
    command: sh -c "yarn && yarn sequelize-cli db:migrate && (yarn dev & yarn start-queue)"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=777
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --bind redis
